tas2580_usermap_index:
    pattern: /usermap/
    defaults: { _controller: tas2580.usermap.main:index }
tas2580_usermap_position:
    pattern: /usermap/position
    defaults: { _controller: tas2580.usermap.ajax:position }
tas2580_usermap_get_marker:
    pattern: /usermap/marker
    defaults: { _controller: tas2580.usermap.ajax:marker }
tas2580_usermap_search:
    pattern: /usermap/search
    defaults: { _controller: tas2580.usermap.main:search }
tas2580_usermap_search_page:
    pattern: /usermap/search/page-{start}.html
    defaults: { _controller: tas2580.usermap.main:search }
tas2580_usermap_get_distance:
    pattern: /usermap/distance
    defaults: { _controller: tas2580.usermap.ajax:distance }
tas2580_usermap_add_place:
    pattern: /usermap/add
    defaults: { _controller: tas2580.usermap.thing:add_place }
tas2580_usermap_place:
    pattern: /usermap/place/{id}
    defaults: { _controller: tas2580.usermap.thing:view_place }
tas2580_usermap_placelist:
    pattern: /usermap/placelist/{id}
    defaults: { _controller: tas2580.usermap.thing:list_places }
tas2580_usermap_place_delete:
    pattern: /usermap/place/{id}/delete
    defaults: { _controller: tas2580.usermap.thing:delete_place }
tas2580_usermap_place_edit:
    pattern: /usermap/place/{id}/edit
    defaults: { _controller: tas2580.usermap.thing:edit_place }
tas2580_usermap_comment:
    pattern: /usermap/comment/add/{id}
    defaults: { _controller: tas2580.usermap.comment:add }
tas2580_usermap_comment_edit:
    pattern: /usermap/comment/edit/{id}
    defaults: { _controller: tas2580.usermap.comment:edit }
tas2580_usermap_comment_delete:
    pattern: /usermap/comment/delete/{id}
    defaults: { _controller: tas2580.usermap.comment:delete }
