tas2580_usermap_index:
    path: /usermap/
    defaults: { _controller: tas2580.usermap.main:index }
tas2580_usermap_position:
    path: /usermap/position
    defaults: { _controller: tas2580.usermap.ajax:position }
tas2580_usermap_get_marker:
    path: /usermap/marker
    defaults: { _controller: tas2580.usermap.ajax:marker }
tas2580_usermap_search:
    path: /usermap/search
    defaults: { _controller: tas2580.usermap.main:search }
tas2580_usermap_search_page:
    path: /usermap/search/page-{start}.html
    defaults: { _controller: tas2580.usermap.main:search }
tas2580_usermap_get_distance:
    path: /usermap/distance
    defaults: { _controller: tas2580.usermap.ajax:distance }
tas2580_usermap_add_place:
    path: /usermap/add
    defaults: { _controller: tas2580.usermap.place:add }
tas2580_usermap_place:
    path: /usermap/place/{id}
    defaults: { _controller: tas2580.usermap.place:view }
tas2580_usermap_placelist:
    path: /usermap/placelist/{id}
    defaults: { _controller: tas2580.usermap.place:list_all }
tas2580_usermap_place_delete:
    path: /usermap/place/delete/{id}
    defaults: { _controller: tas2580.usermap.place:delete }
tas2580_usermap_place_edit:
    path: /usermap/place/edit/{id}
    defaults: { _controller: tas2580.usermap.place:edit }
tas2580_usermap_comment:
    path: /usermap/comment/add/{id}
    defaults: { _controller: tas2580.usermap.comment:add }
tas2580_usermap_comment_edit:
    path: /usermap/comment/edit/{id}
    defaults: { _controller: tas2580.usermap.comment:edit }
tas2580_usermap_comment_delete:
    path: /usermap/comment/delete/{id}
    defaults: { _controller: tas2580.usermap.comment:delete }
