parameters:
    tables.usermap.places: %core.table_prefix%usermap_places
    tables.usermap.place_types: %core.table_prefix%usermap_place_types
    tables.usermap.comments: %core.table_prefix%usermap_place_comments
    tables.usermap.maps: %core.table_prefix%usermap_maps
services:
    tas2580.usermap.main:
        class: tas2580\usermap\controller\main
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@dispatcher'
            - '@controller.helper'
            - '@pagination'
            - '@path_helper'
            - '@request'
            - '@ext.manager'
            - '@user'
            - '@template'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.usermap.places%'
            - '%tables.usermap.place_types%'
            - '%tables.usermap.maps%'
    tas2580.usermap.ajax:
        class: tas2580\usermap\controller\ajax
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@dispatcher'
            - '@controller.helper'
            - '@request'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.usermap.places%'
            - '%tables.usermap.place_types%'
    tas2580.usermap.place:
        class: tas2580\usermap\controller\place
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@dispatcher'
            - '@controller.helper'
            - '@pagination'
            - '@path_helper'
            - '@request'
            - '@ext.manager'
            - '@user'
            - '@template'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.usermap.places%'
            - '%tables.usermap.place_types%'
            - '%tables.usermap.comments%'
            - '%tables.usermap.maps%'
    tas2580.usermap.comment:
        class: tas2580\usermap\controller\comment
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@request'
            - '@user'
            - '@template'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.usermap.places%'
            - '%tables.usermap.comments%'
    tas2580.usermap.listener:
        class: tas2580\usermap\event\listener
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@path_helper'
            - '@ext.manager'
            - '@request'
            - '@template'
            - '@user'
            - '%tables.usermap.maps%'
        tags:
            - '{ name: event.listener }'
    tas2580.usermap.listener_acp:
        class: tas2580\usermap\event\listener_acp
        arguments:
            - '@ext.manager'
            - '@path_helper'
            - '@request'
            - '@user'
            - '@template'
            - '%core.root_path%'
        tags:
            - '{ name: event.listener }'
    tas2580.usermap.listener_ucp:
        class: tas2580\usermap\event\listener_ucp
        arguments:
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@request'
            - '@user'
            - '@template'
            - '%core.root_path%'
        tags:
            - '{ name: event.listener }'