parameters:
    tables.usermap.things: %core.table_prefix%usermap_things
    tables.usermap.place_types: %core.table_prefix%usermap_place_types

services:
    tas2580.usermap.main:
        class: tas2580\usermap\controller\main
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @dispatcher
            - @controller.helper
            - @pagination
            - @path_helper
            - @request
            - @ext.manager
            - @user
            - @template
            - %core.root_path%
            - %core.php_ext%
            - %tables.usermap.things%
            - %tables.usermap.place_types%
    tas2580.usermap.ajax:
        class: tas2580\usermap\controller\ajax
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @dispatcher
            - @controller.helper
            - @request
            - @user
            - %core.root_path%
            - %core.php_ext%
            - %tables.usermap.things%
            - %tables.usermap.place_types%
    tas2580.usermap.thing:
        class: tas2580\usermap\controller\thing
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @dispatcher
            - @controller.helper
            - @pagination
            - @path_helper
            - @request
            - @ext.manager
            - @user
            - @template
            - %core.root_path%
            - %core.php_ext%
            - %tables.usermap.things%
            - %tables.usermap.place_types%
    tas2580.usermap.listener:
        class: tas2580\usermap\event\listener
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @controller.helper
            - @path_helper
            - @ext.manager
            - @request
            - @template
            - @user
        tags:
            - { name: event.listener }
    tas2580.usermap.listener_acp:
        class: tas2580\usermap\event\listener_acp
        arguments:
            - @ext.manager
            - @path_helper
            - @request
            - @user
            - @template
            - %core.root_path%
        tags:
            - { name: event.listener }
    tas2580.usermap.listener_ucp:
        class: tas2580\usermap\event\listener_ucp
        arguments:
            - @auth
            - @config
            - @controller.helper
            - @request
            - @user
            - @template
            - %core.root_path%
        tags:
            - { name: event.listener }